version: 2
jobs:
   build:
     working_directory: ~/recipe
     docker:
      - image: circleci/node:9.11.1-browsers
     steps:
      - checkout
      - run: 
          name: npm install
          command: npm install
          working_directory: ~/recipe
      - run:
          name: run tests
          command: ./node_modules/.bin/ng test --single-run
          working_directory: ~/recipe
      - store_test_results:
          path: ~/recipe/junit
      - store_artifacts:
          path: ~/recipe/junit
      - run:
          name: build
          command: ./node_modules/.bin/ng build --prod
          working_directory: ~/recipe
      - run:
          name: typescript install?
          command: npm install -g typescript
      - run:
          name: function npm install
          command: npm install
          working_directory: ~/recipe/functions
      - run:
          name: build function
          command: npm --prefix functions run build
          working_directory: ~/recipe
      - deploy:
          name: deploy to firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive
          working_directory: ~/recipe
       